### ISSUE TITLE
Feature - Event enrichment with dependency details

### ISSUE THREAD

**Issue by mcbsdEU** [sensu-extensions/sensu-extensions-check-dependencies#10]
Hi,

I refer a bit to my comment in [1620](https://github.com/sensu/sensu/issues/1620).

This extension could enrich event with attribute storing list of checks which were actually found as dependencies (not all listed in definition, just actual ones from the list)
The attribute might be used in custom correlation methods.

**Imagine this use-case:**
-web_service check is configured with dependency mysql.
-mysql goes down and right away web-service fails due to that.
-mysql event is passing respective handler, web-service event is filtered
-event is registered by sensu-server for both of them (etc. they are both red in uchiwa)
-both checks are configured with auto_resolve: false

**What happens next:**
-subjected handler passed event to 3rd party ticketing dashboard and ticketid was assigned
-problem is fixed and operator resolves "incident" in 3rd party ticketing dashboard
-3rd dashboard resolves event registered in sensu-server, via API

**Result:**
-check mysql is OK now
-root cause event(mysql) is resolved
#-web_service event is hanging red in uchiwa dashboard# - and that is the problem

**Possible solution:**
If event was enriched with attribute as described very above AND this extension has "negate" filter attribute working (and set to true) - "child" event could be routed to 3rd party ticketing dashboard as well but then some internal logic append given event to existing root cause incident(created by mysql root cause event) based on listed checks in attribute.
As 3rd party dashboard (or whatever and however you name it) is aware now about relation, it is also able to resolve "child" events of root event, same way, via API.

What is your opinion about this?
Thanks in advance

**Comment by portertech** [comment]
Filters are not intended for altering/changing/mutating/enriching event data.

**Comment by amdprophet** [comment]
You may be able to accomplish what you're seeking by using mutators to enrich your events with additional data. Please note that this may cause performance implications at scale.

**Comment by mcbsdEU** [comment]
Thanks for feedback
