### ISSUE TITLE
Error - unknown filter

### ISSUE THREAD

**Issue by mcbsdEU** [sensu-extensions/sensu-extensions-check-dependencies#5]
Hi,

After implementation according readme I get following error:
"error","message":"unknown filter","filter_name":"check_dependencies"

Is this due to fact that this extension is just for Sensu Enterprise?
If so, it could be better to note it in readme in addtion to https://sensuapp.org/docs/latest/enterprise/filters/check-dependencies.html

Thanks

**Comment by mcbsdEU** [comment]
+ one cosmetic thing:
In readme part "Edit /etc/sensu/conf.d/extensions.json to load it" -> there is one bracket "}" missing.

**Comment by cwjohnston** [comment]
hi @mcbsdEU, thanks for bringing the invalid JSON to my attention. I've fixed it in 81c48bc35624a58772c4c40a961916cf08c26aa6.

This extension is based on the Sensu Enterprise implementation you referenced. It is expected to work in Sensu Core when properly installed and will be [added as a built-in extension in a future version of Sensu Core](https://github.com/sensu/sensu-extensions/pull/14).

In working up a reply to this issue I see that we've shipped the current release in an unusable state, this is likely why the filter is unknown in your environment. Specifically we renamed the gem project but didn't rename the extension Ruby file to match, so I've opened https://github.com/sensu-extensions/sensu-extensions-check-dependencies/issues/6 to track that.

**Comment by mcbsdEU** [comment]
Thanks!

**Comment by cwjohnston** [comment]
@mcbsdEU version 1.0.1 is now on rubygems, please let us know if you have any further issues.

**Comment by mcbsdEU** [comment]
Hi,

I can confirm all is working now as expected.
Thanks
