### ISSUE TITLE
Negate attribute - where to place it?

### ISSUE THREAD

**Issue by mcbsdEU** [sensu-extensions/sensu-extensions-check-dependencies#9]
Hi,

this veery useful extension is applied as a filter at the end.
Filter, however, has option to include negate attribute - how can I apply that to this extension?
I tried it as attribute inside extensions.json:
```
{
  "extensions": {
    "check-dependencies": {
      "version": "1.0.1",
      "negate": true
    }
  }
}
```
-well, that was not working. I can't see any other place where I could try to insert this attribute.

So, from my point of view, when it is applied as a filter, it should somehow consume negate attribute which is standard filter attribute.

Thanks

**Comment by amdprophet** [comment]
Hi @mcbsdEU,

This is possible but does not currently appear to be documented outside of the `sensu-extension` source code. You should be able to add filter attributes via the `definition` attribute. e.g.

```
{
  "extensions": {
    "check-dependencies": {
      "version": "1.0.1",
      "definition": {
        "negate": true
      }
    }
  }
}
```

Please let me know if this addresses the issue.

**Comment by mcbsdEU** [comment]
Ok, thanks. I have no room to test this now, but when I come around to play with this, I'll give it a try.
